### ISSUE TITLE
We need a Style Guide.

### ISSUE THREAD

**Issue by RigidStudios** [AetherInteractiveLtd/Tina#7]
https://github.com/AetherInteractiveLtd/Tina/blob/a52353206b48977025eac18d35518293ee4ad1fd/src/lib/net/remote.ts#L8

@ffrostflame

**Comment by christopher-buss** [comment]
We should just use the default eslint which is already one of the suggested extensions. It should already conform to standard Roblox-TS guidelines rather than needing our own, we just need to ensure that all users have it installed and are using it.

To facilate this, a CI pipeline running this should be setup as soon as possible so that we can ensure no one can check in work unless they already have it running locally.

**Comment by siriuslatte** [comment]
Christopher right, this has already been done by @RigidStudios, nothing else to add so this comment will close the issue now.
